# Omni Cyber Guard  -  one-shot local setup for Windows (PowerShell)
# Powered by Omni Digital Solution
#
# Run this from inside the omni-cyber-guard folder:
#   .\setup.ps1
#
# It will:
#   1. Ask for the admin email/password you want to log in with (or reuse them if you've already run it)
#   2. Generate a random SECRET_KEY and write backend\.env and frontend\.env.local
#   3. Build and start Docker containers (postgres, redis, backend, worker, frontend)
#   4. Wait for the backend to become healthy
#   5. Run database migrations
#   6. Print the URL to open and the login you set

$ErrorActionPreference = "Stop"

function Write-Step($msg) { Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "    $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "    $msg" -ForegroundColor Yellow }
function Write-Err($msg)  { Write-Host "    $msg" -ForegroundColor Red }

# --- 0. Sanity checks ---
Write-Step "Checking prerequisites"

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Err "Docker was not found on PATH. Install Docker Desktop first: https://www.docker.com/products/docker-desktop/"
    exit 1
}
try {
    docker info | Out-Null
} catch {
    Write-Err "Docker is installed but not running. Start Docker Desktop, wait for it to say 'Engine running', then re-run this script."
    exit 1
}
Write-Ok "Docker is installed and running."

if (-not (Test-Path ".\backend\requirements.txt") -or -not (Test-Path ".\frontend\package.json")) {
    Write-Err "This script must be run from inside the omni-cyber-guard folder (backend\ and frontend\ not found here)."
    exit 1
}

# --- 1. Collect / reuse admin credentials ---
Write-Step "Admin account setup"

$envPath = ".\backend\.env"
$existingEmail = $null
$existingPassword = $null

if (Test-Path $envPath) {
    $existing = Get-Content $envPath -Raw
    if ($existing -match "FIRST_SUPERADMIN_EMAIL=(.+)") { $existingEmail = $matches[1].Trim() }
    if ($existing -match "FIRST_SUPERADMIN_PASSWORD=(.+)") { $existingPassword = $matches[1].Trim() }
}

if ($existingEmail -and $existingPassword) {
    Write-Ok "backend\.env already exists with an admin account ($existingEmail). Reusing it."
    Write-Warn "Delete backend\.env first if you want to set a different email/password."
    $adminEmail = $existingEmail
    $adminPassword = $existingPassword
} else {
    $adminEmail = Read-Host "Enter the email you want to log in with"
    $securePw = Read-Host "Enter the password you want to log in with (min 8 characters)" -AsSecureString
    $adminPassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($securePw)
    )
    if ($adminPassword.Length -lt 8) {
        Write-Err "Password must be at least 8 characters."
        exit 1
    }
}

# --- 2. Write env files ---
Write-Step "Writing environment files"

function New-RandomSecret {
    $bytes = New-Object byte[] 48
    [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [Convert]::ToBase64String($bytes) -replace '[^a-zA-Z0-9]', ''
}

$secretKey = New-RandomSecret

@"
# Omni Cyber Guard - Backend Environment (generated by setup.ps1)
ENVIRONMENT=development
SECRET_KEY=$secretKey
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7
DATABASE_URL=postgresql://ocg_user:ocg_password@postgres:5432/omni_cyber_guard
REDIS_URL=redis://redis:6379/0
BACKEND_CORS_ORIGINS=["http://localhost:3000"]
FIRST_SUPERADMIN_EMAIL=$adminEmail
FIRST_SUPERADMIN_PASSWORD=$adminPassword
"@ | Set-Content -Path $envPath -Encoding UTF8

Write-Ok "backend\.env written."

if (-not (Test-Path ".\frontend\.env.local")) {
    "NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api/v1" | Set-Content ".\frontend\.env.local" -Encoding UTF8
    Write-Ok "frontend\.env.local written."
} else {
    Write-Ok "frontend\.env.local already exists, leaving it as-is."
}

# --- 3. Build and start containers ---
Write-Step "Building and starting containers (this can take several minutes the first time)"
docker compose up --build -d
if ($LASTEXITCODE -ne 0) {
    Write-Err "docker compose up failed. Scroll up for the error, or paste it back for help debugging."
    exit 1
}
Write-Ok "Containers started."

# --- 4. Wait for backend health ---
function Wait-ForBackendHealth {
    Write-Step "Waiting for the backend API to become healthy"
    $healthy = $false
    for ($i = 0; $i -lt 60; $i++) {
        try {
            $resp = Invoke-WebRequest -Uri "http://localhost:8000/api/health" -UseBasicParsing -TimeoutSec 2
            if ($resp.StatusCode -eq 200) { $healthy = $true; break }
        } catch { Start-Sleep -Seconds 2 }
    }
    return $healthy
}

if (-not (Wait-ForBackendHealth)) {
    Write-Err "Backend didn't become healthy after 2 minutes. Run 'docker compose logs backend' to see why, or paste the output back for help."
    exit 1
}
Write-Ok "Backend is up."

# --- 5. Run migrations ---
Write-Step "Running database migrations"

function Invoke-Migrations {
    $hasMigrations = (Get-ChildItem ".\backend\alembic\versions" -Filter "*.py" -ErrorAction SilentlyContinue | Measure-Object).Count -gt 0
    if (-not $hasMigrations) {
        Write-Ok "No migration files yet - generating the initial schema migration."
        docker compose exec -T backend alembic revision --autogenerate -m "initial schema"
    } else {
        Write-Ok "Migration files already exist, skipping generation."
    }
    docker compose exec -T backend alembic upgrade head
    return $LASTEXITCODE
}

$migrationExitCode = Invoke-Migrations

if ($migrationExitCode -ne 0) {
    # The most common cause: the database remembers a migration revision whose
    # .py file no longer exists on disk (e.g. after an image rebuild wiped an
    # untracked file). There's no data worth preserving yet at this stage of
    # setup, so the reliable fix is a clean slate: wipe the Postgres volume
    # and any leftover migration files, then start over from scratch.
    Write-Warn "Migration failed - likely a stale migration-history mismatch. Resetting the database and retrying from a clean slate..."
    docker compose down -v
    Get-ChildItem ".\backend\alembic\versions" -Filter "*.py" -ErrorAction SilentlyContinue | Remove-Item -Force
    docker compose up --build -d
    if (-not (Wait-ForBackendHealth)) {
        Write-Err "Backend didn't come back up after the reset. Run 'docker compose logs backend' or paste the output back for help."
        exit 1
    }
    $migrationExitCode = Invoke-Migrations
    if ($migrationExitCode -ne 0) {
        Write-Err "Migrations still failed after a clean reset. Run 'docker compose logs backend' or paste the error back for help."
        exit 1
    }
    Write-Ok "Reset and repaired successfully."
}

Write-Ok "Migrations applied."

# --- 6. Done ---
Write-Step "All set"
Write-Host ""
Write-Host "  Open:      http://localhost:3000" -ForegroundColor White
Write-Host "  API docs:  http://localhost:8000/api/docs" -ForegroundColor White
Write-Host "  Login:     $adminEmail" -ForegroundColor White
Write-Host "  Password:  (what you just entered)" -ForegroundColor White
Write-Host ""
Write-Host "  To scan your real LAN (not just the Docker network), see the" -ForegroundColor Yellow
Write-Host "  'Running the scan worker natively' section in README.md." -ForegroundColor Yellow
Write-Host ""
Write-Host "  To stop everything:  docker compose down" -ForegroundColor DarkGray
Write-Host "  To view logs:        docker compose logs -f" -ForegroundColor DarkGray
