"""Add ai playbook to incident

Revision ID: 06c776690c82
Revises: 6de7e6a26052
Create Date: 2026-08-18 16:00:42.034894

"""
from alembic import op
import sqlalchemy as sa


revision = '06c776690c82'
down_revision = '6de7e6a26052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
