"""cascade_delete_scans

Revision ID: 3ebd9d23ee73
Revises: 61bbdc0f46e4
Create Date: 2026-08-17 15:25:01.219503

"""
from alembic import op
import sqlalchemy as sa


revision = '3ebd9d23ee73'
down_revision = '61bbdc0f46e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assets_scan_job_id_fkey', 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'scan_jobs', ['scan_job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('findings_scan_job_id_fkey', 'findings', type_='foreignkey')
    op.create_foreign_key(None, 'findings', 'scan_jobs', ['scan_job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.create_foreign_key('findings_scan_job_id_fkey', 'findings', 'scan_jobs', ['scan_job_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key('assets_scan_job_id_fkey', 'assets', 'scan_jobs', ['scan_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
