"""phase_11_discovery_modules

Revision ID: 42e91f847792
Revises: a5ff3fd8cd85
Create Date: 2026-08-21 17:03:00.191448

"""
from alembic import op
import sqlalchemy as sa


revision = '42e91f847792'
down_revision = 'a5ff3fd8cd85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_surface_domains',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('ip_addresses', sa.String(length=512), server_default='', nullable=False),
    sa.Column('registrar', sa.String(length=255), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('cert_issuer', sa.String(length=255), server_default='', nullable=False),
    sa.Column('cert_valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cert_valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_surface_domains_domain_name'), 'attack_surface_domains', ['domain_name'], unique=False)
    op.create_index(op.f('ix_attack_surface_domains_organization_id'), 'attack_surface_domains', ['organization_id'], unique=False)
    op.create_table('cloud_resources',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), server_default='', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='ACTIVE', nullable=False),
    sa.Column('compliance_status', sa.String(length=50), server_default='UNKNOWN', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_resources_organization_id'), 'cloud_resources', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_provider'), 'cloud_resources', ['provider'], unique=False)
    op.create_table('identity_profiles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('privilege_level', sa.String(length=50), server_default='USER', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_profiles_email'), 'identity_profiles', ['email'], unique=False)
    op.create_index(op.f('ix_identity_profiles_organization_id'), 'identity_profiles', ['organization_id'], unique=False)
    
    # RLS Policies
    for table in ['attack_surface_domains', 'cloud_resources', 'identity_profiles']:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY {table}_tenant_isolation_policy ON {table}
            AS PERMISSIVE FOR ALL
            TO PUBLIC
            USING (organization_id = current_setting('app.current_tenant', true)::uuid)
            WITH CHECK (organization_id = current_setting('app.current_tenant', true)::uuid)
        """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_profiles_organization_id'), table_name='identity_profiles')
    op.drop_index(op.f('ix_identity_profiles_email'), table_name='identity_profiles')
    op.drop_table('identity_profiles')
    op.drop_index(op.f('ix_cloud_resources_provider'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_organization_id'), table_name='cloud_resources')
    op.drop_table('cloud_resources')
    op.drop_index(op.f('ix_attack_surface_domains_organization_id'), table_name='attack_surface_domains')
    op.drop_index(op.f('ix_attack_surface_domains_domain_name'), table_name='attack_surface_domains')
    op.drop_table('attack_surface_domains')
    # ### end Alembic commands ###
