"""add_incident_model

Revision ID: 61bbdc0f46e4
Revises: b3faca151c76
Create Date: 2026-08-17 14:06:24.049647

"""
from alembic import op
import sqlalchemy as sa


revision = '61bbdc0f46e4'
down_revision = 'b3faca151c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
