"""Add engine to scan_job

Revision ID: 6de7e6a26052
Revises: 492f1b6f5d4b
Create Date: 2026-08-18 15:48:25.722484

"""
from alembic import op
import sqlalchemy as sa


revision = '6de7e6a26052'
down_revision = '492f1b6f5d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('engine', sa.String(length=32), server_default='nmap', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_jobs', 'engine')
    # ### end Alembic commands ###
