"""Add scan_job_id to assets and findings

Revision ID: b3faca151c76
Revises: e88182b329aa
Create Date: 2026-08-17 12:47:22.817720

"""
from alembic import op
import sqlalchemy as sa


revision = 'b3faca151c76'
down_revision = 'e88182b329aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('scan_job_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_assets_scan_job_id'), 'assets', ['scan_job_id'], unique=False)
    op.create_foreign_key(None, 'assets', 'scan_jobs', ['scan_job_id'], ['id'], ondelete='SET NULL')
    op.add_column('findings', sa.Column('scan_job_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_findings_scan_job_id'), 'findings', ['scan_job_id'], unique=False)
    op.create_foreign_key(None, 'findings', 'scan_jobs', ['scan_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # The autogenerated `op.drop_constraint(None, ...)` calls that stood here
    # could not be compiled — an unnamed constraint has no name to drop — which
    # made the whole chain irreversible from this point down. They were also
    # redundant: dropping the column drops the foreign key with it.
    op.drop_index(op.f('ix_findings_scan_job_id'), table_name='findings')
    op.drop_column('findings', 'scan_job_id')
    op.drop_index(op.f('ix_assets_scan_job_id'), table_name='assets')
    op.drop_column('assets', 'scan_job_id')
    # ### end Alembic commands ###
