"""Add enterprise settings

Revision ID: c13705bb69fc
Revises: d3966aec788e
Create Date: 2026-08-19 12:42:22.341558

"""
from alembic import op
import sqlalchemy as sa


revision = 'c13705bb69fc'
down_revision = 'd3966aec788e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('slack_webhook_url', sa.String(length=512), nullable=True))
    op.add_column('organizations', sa.Column('teams_webhook_url', sa.String(length=512), nullable=True))
    op.add_column('organizations', sa.Column('sso_provider', sa.String(length=50), server_default='none', nullable=False))
    op.add_column('organizations', sa.Column('sso_metadata_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'sso_metadata_url')
    op.drop_column('organizations', 'sso_provider')
    op.drop_column('organizations', 'teams_webhook_url')
    op.drop_column('organizations', 'slack_webhook_url')
    # ### end Alembic commands ###
