"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Topbar } from "@/components/layout/topbar";
import { AlertOctagon, Download, Info, Plus, Shield, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { api } from "@/lib/api";
import { cn } from "@/lib/utils";

interface BlockedIP {
  id: string;
  ip_address: string;
  reason: string;
  status: "recommended" | "enforced" | "expired";
  created_at: string;
}

interface EnforcementInfo {
  platform_enforces_blocks: boolean;
  explanation: string;
  passive_monitor: { available: boolean; running: boolean; events_in_window: number };
}

const STATUS_STYLES: Record<BlockedIP["status"], string> = {
  recommended: "border-orange-500/40 bg-orange-500/10 text-orange-400",
  enforced: "border-green-500/40 bg-green-500/10 text-green-400",
  expired: "border-border bg-surface text-muted",
};

function downloadText(filename: string, contents: string) {
  const blob = new Blob([contents], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

export default function InfrastructurePage() {
  const queryClient = useQueryClient();
  const [newIp, setNewIp] = useState("");
  const [reason, setReason] = useState("");
  const [error, setError] = useState<string | null>(null);

  const { data: blockedIps = [] } = useQuery({
    queryKey: ["blockedIps"],
    queryFn: () => api.get<BlockedIP[]>("/infrastructure/blocked-ips"),
  });

  const { data: enforcement } = useQuery({
    queryKey: ["enforcementInfo"],
    queryFn: () => api.get<EnforcementInfo>("/infrastructure/enforcement"),
  });

  const invalidate = () => queryClient.invalidateQueries({ queryKey: ["blockedIps"] });

  const blockMutation = useMutation({
    mutationFn: (data: { ip: string; reason: string }) =>
      api.post("/infrastructure/blocked-ips", data),
    onSuccess: () => {
      invalidate();
      setNewIp("");
      setReason("");
      setError(null);
    },
    onError: (err: Error) => setError(err.message),
  });

  const statusMutation = useMutation({
    mutationFn: ({ id, status }: { id: string; status: string }) =>
      api.patch(`/infrastructure/blocked-ips/${id}`, { status }),
    onSuccess: invalidate,
  });

  const removeMutation = useMutation({
    mutationFn: (id: string) => api.delete(`/infrastructure/blocked-ips/${id}`),
    onSuccess: invalidate,
  });

  const exportIptables = () => {
    const lines = [
      "#!/bin/sh",
      "# Generated by Omni Cyber Guard from the current blocklist.",
      "# Review every rule before applying it to a production host.",
      "set -e",
      "",
      ...blockedIps.map(
        (entry) => `iptables -A INPUT -s ${entry.ip_address} -j DROP   # ${entry.reason.replace(/\n/g, " ")}`
      ),
    ];
    downloadText("omni-blocklist-iptables.sh", lines.join("\n") + "\n");
  };

  const exportPowerShell = () => {
    const lines = [
      "# Generated by Omni Cyber Guard from the current blocklist.",
      "# Review every rule before applying it to a production host.",
      "",
      ...blockedIps.map(
        (entry) =>
          `New-NetFirewallRule -DisplayName "OCG block ${entry.ip_address}" ` +
          `-Direction Inbound -Action Block -RemoteAddress ${entry.ip_address}  # ${entry.reason.replace(/\n/g, " ")}`
      ),
    ];
    downloadText("omni-blocklist-firewall.ps1", lines.join("\n") + "\n");
  };

  return (
    <>
      <Topbar title="Infrastructure Protection" />
      <main className="flex-1 space-y-6 overflow-y-auto p-6">
        <div>
          <h1 className="text-2xl font-bold text-ink">Blocklist &amp; Mitigation</h1>
          <p className="text-sm text-muted">
            Record which addresses should be blocked, why, and whether the rule is live upstream.
          </p>
        </div>

        <div className="flex gap-3 rounded-xl border border-primary/30 bg-primary/5 p-4">
          <Info className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
          <div className="space-y-1">
            <p className="text-sm font-semibold text-ink">Omni Cyber Guard does not interrupt traffic</p>
            <p className="text-sm leading-relaxed text-muted">
              {enforcement?.explanation ??
                "Block decisions are recorded here with their justification. Apply the rule at your firewall, edge ACL or host firewall, then mark the entry as enforced."}
            </p>
          </div>
        </div>

        <div className="grid gap-6 md:grid-cols-2">
          <div className="rounded-xl border border-border bg-surface p-6 shadow-sm">
            <h3 className="mb-4 flex items-center gap-2 font-semibold text-ink">
              <Shield className="h-5 w-5 text-primary" /> Add to blocklist
            </h3>
            <div className="space-y-4">
              <div>
                <label className="mb-1 block text-xs text-muted">IP address</label>
                <input
                  value={newIp}
                  onChange={(e) => setNewIp(e.target.value)}
                  className="w-full rounded-md border border-border bg-surface-hover px-3 py-2 text-sm text-ink focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                  placeholder="e.g. 192.168.1.100"
                />
              </div>
              <div>
                <label className="mb-1 block text-xs text-muted">Reason</label>
                <input
                  value={reason}
                  onChange={(e) => setReason(e.target.value)}
                  className="w-full rounded-md border border-border bg-surface-hover px-3 py-2 text-sm text-ink focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                  placeholder="e.g. Repeated SSH authentication failures"
                />
              </div>
              {error && <p className="text-sm text-critical">{error}</p>}
              <Button
                onClick={() => newIp && blockMutation.mutate({ ip: newIp, reason: reason || "Manual block" })}
                disabled={!newIp || blockMutation.isPending}
                className="w-full"
              >
                <Plus className="mr-2 h-4 w-4" /> Record block decision
              </Button>
            </div>
          </div>

          <div className="rounded-xl border border-border bg-surface p-6 shadow-sm">
            <h3 className="mb-4 flex items-center gap-2 font-semibold text-ink">
              <Download className="h-5 w-5 text-primary" /> Export firewall rules
            </h3>
            <p className="mb-4 text-sm text-muted">
              Generates a script containing one rule per blocklist entry, for you to review and apply.
            </p>
            <div className="flex flex-col space-y-2">
              <Button variant="outline" className="justify-start" onClick={exportIptables} disabled={blockedIps.length === 0}>
                <Download className="mr-2 h-4 w-4" /> iptables (Linux)
              </Button>
              <Button variant="outline" className="justify-start" onClick={exportPowerShell} disabled={blockedIps.length === 0}>
                <Download className="mr-2 h-4 w-4" /> Windows Firewall (PowerShell)
              </Button>
            </div>
          </div>
        </div>

        <div className="overflow-hidden rounded-xl border border-border bg-surface">
          <div className="flex items-center justify-between border-b border-border p-4">
            <h2 className="flex items-center gap-2 text-lg font-semibold text-ink">
              <AlertOctagon className="h-5 w-5 text-red-500" /> Blocklist
            </h2>
            <span className="text-xs text-muted">{blockedIps.length} entr{blockedIps.length === 1 ? "y" : "ies"}</span>
          </div>

          <div className="divide-y divide-border">
            {blockedIps.length === 0 ? (
              <div className="p-8 text-center text-muted">No addresses on the blocklist.</div>
            ) : (
              blockedIps.map((entry) => (
                <div key={entry.id} className="flex items-center justify-between gap-4 p-4 hover:bg-surface-hover/50">
                  <div className="min-w-0">
                    <div className="flex items-center gap-2">
                      <p className="font-mono font-semibold text-ink">{entry.ip_address}</p>
                      <span className={cn("rounded-full border px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider", STATUS_STYLES[entry.status])}>
                        {entry.status}
                      </span>
                    </div>
                    <p className="truncate text-sm text-muted">
                      {entry.reason} • added {new Date(entry.created_at).toLocaleString()}
                    </p>
                  </div>
                  <div className="flex shrink-0 gap-2">
                    {entry.status !== "enforced" && (
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => statusMutation.mutate({ id: entry.id, status: "enforced" })}
                        disabled={statusMutation.isPending}
                      >
                        Mark enforced
                      </Button>
                    )}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => removeMutation.mutate(entry.id)}
                      disabled={removeMutation.isPending}
                      className="border-critical/50 text-critical hover:bg-critical/10"
                    >
                      <XCircle className="mr-2 h-4 w-4" /> Remove
                    </Button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </main>
    </>
  );
}
